# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose Browser: chrome, edge'
        required: true
        default: 'chrome'
      suite:
        description: 'Choose Suite: FeaturesSuite, RegressionSuite'
        required: true
        default: 'RegressionSuite'
      transactionCurrencies:
        description: 'Choose Currencies(1 or more): Dollar,Rupee,Pound'
        required: true
        default: 'Dollar,Rupee,Pound'
      depositAmount:
        description: 'Choose the amount to deposit: 1-...'
        required: true
        default: '1000'
      withdrawlAmount:
        description: 'Choose the amount to withdraw less then the deposited amount'
        required: true
        default: '999'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Update Properties
        run: java -cp target/myapp.jar sharedData.transcations.Transactions ${{ github.event.inputs.transactionCurrencies }} ${{ github.event.inputs.depositAmount }} ${{ github.event.inputs.withdrawlAmount }}

      - name: Run Automation Tests
        run: mvn clean install -DcIcD=true -Dbrowser=${{ github.event.inputs.browser }} -DsuiteXmlFile=suites/${{ github.event.inputs.suite }} -PCustomSuite

      - name: Publish suite results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: SuiteResults
          path: |
            target/logs/suitetest.log