# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose Browser: chrome, edge'
        required: true
        default: 'chrome'
      suite:
        description: 'Choose Suite: FeaturesSuite, RegressionSuite'
        required: true
        default: 'RegressionSuite'
      deposit_withdraw:
        description: 'Input deposit/withdraw amounts for different currencies'
        required: true
        default:
          Dollar:
            deposit: '1001'
            withdraw: '500'
          Pound:
            deposit: '1001'
            withdraw: '500'
          Rupee:
            deposit: '1001'
            withdraw: '500'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Run Automation Tests
        run: mvn clean install -DcIcD=true -Dbrowser=${{ github.event.inputs.browser }} -DsuiteXmlFile=suites/${{ github.event.inputs.suite }} -Ddeposit_withdraw=${{ github.event.inputs.deposit_withdraw }}-PCustomSuite

      - name: Publish suite results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: SuiteResults
          path: |
            target/logs/suitetest.log